services:
  bun:
    build:
      context: ./bun
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - ./bun/root/.bash_history:/root/.bash_history:cached
      - ./bun/root/.bashrc:/root/.bashrc:cached
    networks:
      net:

networks:
  net:
